apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-gke
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: github-actions-gke
    spec:
      containers:
      - name: github-actions-gke
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8443
        env:
          - name: PORT
            value: "8443"
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m